version: '3.8'

services:
  apache:
    build: "./apache/"
    ports: 
      - "8080:80"
    volumes:
      - ./public_html/:/var/www/html/
    depends_on:
      - php
      - mysql
    restart: unless-stopped
    networks:
      - frontend
      - backend

  php:
    build: "./php/"
    volumes:
      - ./public_html/:/var/www/html/
    networks:
      - backend
  
  mysql:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
    networks:
      - frontend
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8000:80'
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
    links:
      - mysql
    depends_on:
      - mysql
    networks:
      - frontend

networks:
  frontend:
  backend: